import { join } from 'pathe';
import type {
  AffectedTool,
  E2EPriority,
  E2ETestGenerator,
  Feature,
  ImpactAnalysisResult,
  ProjectStructure,
  RunContext,
  TestCaseResult,
  TestFile,
  TestSuiteResult,
} from '../types';
import type { ResolvedE2EConfig } from '../config';
import { RecursiveImpactAnalyzer } from '../recursive-impact-analyzer';

type GoKind = 'http-server' | 'cli' | 'generic';

interface GoDetection {
  kind: GoKind;
  framework: string;
  /** `go build` target for the server binary, e.g. "." or "./cmd/server". */
  buildTarget: string;
}

/** Sanitize an arbitrary string into a safe Go identifier fragment. */
function goIdent(raw: string): string {
  const cleaned = raw.replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  if (cleaned === '') return 'root';
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}

/**
 * A single `go test -json` event. We only consume the fields we need.
 * @see https://pkg.go.dev/cmd/test2json
 */
interface GoTestEvent {
  Action?: string;
  Package?: string;
  Test?: string;
  Output?: string;
}

/**
 * Parse the newline-delimited JSON stream emitted by `go test -json` into the
 * framework's normalized suite/test model. One suite per package; package-level
 * events (no `Test` field) are folded into a synthetic `<package>` test only
 * when they fail, so a green run reports just its real tests.
 */
export function parseGoTestJson(stdout: string): TestSuiteResult[] {
  const suites = new Map<string, TestSuiteResult>();
  const output = new Map<string, string[]>(); // key: pkg\x00test

  const suiteFor = (pkg: string): TestSuiteResult => {
    let suite = suites.get(pkg);
    if (suite === undefined) {
      suite = { file: pkg, status: 'passed', duration: 0, tests: [] };
      suites.set(pkg, suite);
    }
    return suite;
  };

  for (const line of stdout.split('\n')) {
    const trimmed = line.trim();
    if (trimmed === '' || !trimmed.startsWith('{')) continue;
    let event: GoTestEvent;
    try {
      event = JSON.parse(trimmed) as GoTestEvent;
    } catch {
      continue;
    }
    const pkg = event.Package ?? '<unknown>';
    const key = `${pkg}\x00${event.Test ?? ''}`;

    if (event.Action === 'output' && typeof event.Output === 'string') {
      const buf = output.get(key) ?? [];
      buf.push(event.Output);
      output.set(key, buf);
      continue;
    }

    if (event.Action !== 'pass' && event.Action !== 'fail' && event.Action !== 'skip') {
      continue;
    }

    const suite = suiteFor(pkg);
    const status: TestCaseResult['status'] =
      event.Action === 'pass' ? 'passed' : event.Action === 'skip' ? 'skipped' : 'failed';

    if (event.Test === undefined || event.Test === '') {
      // Package-level result: only surface failures (e.g. build/compile errors).
      if (status === 'failed') {
        suite.status = 'failed';
        suite.tests.push({
          name: `${pkg} (package)`,
          status: 'failed',
          failureMessages: [(output.get(key) ?? []).join('').slice(0, 2000)],
        });
      }
      continue;
    }

    if (status === 'failed') suite.status = 'failed';
    suite.tests.push({
      name: event.Test,
      status,
      failureMessages: status === 'failed' ? [(output.get(key) ?? []).join('').slice(0, 2000)] : [],
    });
  }

  return [...suites.values()];
}

const HTTP_SERVER_TEMPLATE = `//go:build e2e

package e2e

import (
\t"context"
\t"encoding/json"
\t"net"
\t"net/http"
\t"os"
\t"os/exec"
\t"path/filepath"
\t"testing"
\t"time"
)

// Test_{{ident}}_E2E builds and launches the server as a real subprocess, then
// exercises its external HTTP interface and asserts on the parsed JSON response.
//
// AUTO-GENERATED by RunE2ETests (Go http-server template).
// TODO: adjust buildTarget, the request path, and the response assertions to
// match the real service under test.
func Test_{{ident}}_E2E(t *testing.T) {
\tmoduleRoot := {{moduleRoot}}
\tbuildTarget := {{buildTarget}} // e.g. "." or "./cmd/server"

\tfreePort := func() string {
\t\tl, err := net.Listen("tcp", "127.0.0.1:0")
\t\tif err != nil {
\t\t\tt.Fatalf("failed to find a free port: %v", err)
\t\t}
\t\tdefer l.Close()
\t\t_, port, _ := net.SplitHostPort(l.Addr().String())
\t\treturn port
\t}
\twaitForServer := func(addr string, timeout time.Duration) {
\t\tdeadline := time.Now().Add(timeout)
\t\tfor time.Now().Before(deadline) {
\t\t\tconn, err := net.DialTimeout("tcp", addr, 200*time.Millisecond)
\t\t\tif err == nil {
\t\t\t\t_ = conn.Close()
\t\t\t\treturn
\t\t\t}
\t\t\ttime.Sleep(100 * time.Millisecond)
\t\t}
\t\tt.Fatalf("server did not become ready at %s within %s", addr, timeout)
\t}

\t// 1. Build the server binary.
\tbinPath := filepath.Join(t.TempDir(), "server-under-test")
\tbuild := exec.Command("go", "build", "-o", binPath, buildTarget)
\tbuild.Dir = moduleRoot
\tif out, err := build.CombinedOutput(); err != nil {
\t\tt.Fatalf("go build failed: %v\\n%s", err, out)
\t}

\t// 2. Pick a free port and launch the server as a real subprocess.
\tport := freePort()
\taddr := "127.0.0.1:" + port
\tctx, cancel := context.WithCancel(context.Background())
\tdefer cancel()
\tcmd := exec.CommandContext(ctx, binPath)
\tcmd.Dir = moduleRoot
\t// TODO: pass the listen address the way your server expects it.
\tcmd.Env = append(os.Environ(), "PORT="+port, "ADDR="+addr)
\tcmd.Stdout = os.Stdout
\tcmd.Stderr = os.Stderr
\tif err := cmd.Start(); err != nil {
\t\tt.Fatalf("failed to start server: %v", err)
\t}
\tt.Cleanup(func() {
\t\tcancel()
\t\t_ = cmd.Wait()
\t})

\t// 3. Wait until the server is accepting connections.
\twaitForServer(addr, 10*time.Second)

\t// 4. Call the external interface and parse the JSON response.
\tclient := &http.Client{Timeout: 5 * time.Second}
\treq, err := http.NewRequest(http.MethodGet, "http://"+addr+"/", nil) // TODO: real method + path
\tif err != nil {
\t\tt.Fatalf("failed to build request: %v", err)
\t}
\t// TODO: if this endpoint requires authentication, attach a valid credential.
\t// Obtain it the way your service expects — e.g. a test token injected into the
\t// server via cmd.Env above, or by calling your login endpoint first, then:
\t//   req.Header.Set("Authorization", "Bearer "+token)
\tresp, err := client.Do(req)
\tif err != nil {
\t\tt.Fatalf("request failed: %v", err)
\t}
\tdefer resp.Body.Close()

\tif resp.StatusCode != http.StatusOK {
\t\tt.Fatalf("unexpected status: got %d, want 200", resp.StatusCode)
\t}

\tvar body map[string]any
\tif err := json.NewDecoder(resp.Body).Decode(&body); err != nil {
\t\tt.Fatalf("failed to decode JSON response: %v", err)
\t}

\t// TODO: assert on the fields your interface returns, e.g.:
\t//   if body["status"] != "ok" { t.Fatalf("got %v", body["status"]) }
\t_ = body

\t// TODO: if the endpoint is protected, also assert the unauthorized path:
\t//   unauth, _ := http.NewRequest(http.MethodGet, "http://"+addr+"/", nil)
\t//   if r2, err := client.Do(unauth); err == nil {
\t//       defer r2.Body.Close()
\t//       if r2.StatusCode != http.StatusUnauthorized {
\t//           t.Fatalf("want 401 without credentials, got %d", r2.StatusCode)
\t//       }
\t//   }
}
`;

const GENERIC_TEMPLATE = `//go:build e2e

package e2e

import "testing"

// Test_{{ident}}_E2E is an AUTO-GENERATED smoke placeholder by RunE2ETests
// (Go {{kind}} template).
// TODO: replace with a real launch + assertion flow for "{{toolId}}".
func Test_{{ident}}_E2E(t *testing.T) {
\tt.Log("e2e placeholder for {{toolId}}")
}
`;

export class GoGenerator implements E2ETestGenerator {
  readonly id = 'go';

  async detectProjectStructure(root: string): Promise<ProjectStructure | null> {
    const detection = await this.detect(root);
    if (detection === null) return null;
    return { language: 'go', framework: detection.framework, testTool: 'go test', root };
  }

  analyzeImpact(changedFiles: string[], config: ResolvedE2EConfig, projectRoot?: string): ImpactAnalysisResult {
    const filesToAnalyze = config.recursiveAnalysisEnabled
      ? new RecursiveImpactAnalyzer().analyze(
          changedFiles,
          projectRoot ?? process.cwd(),
          'go',
          { maxDepth: config.maxRecursiveDepth },
        )
      : changedFiles;
    const packages = new Set<string>();
    for (const file of filesToAnalyze) {
      const normalized = file.replace(/\\/g, '/');
      if (!normalized.endsWith('.go') || normalized.endsWith('_test.go')) continue;
      const slash = normalized.lastIndexOf('/');
      packages.add(slash === -1 ? '.' : normalized.slice(0, slash));
    }

    const affected: AffectedTool[] = [];
    for (const pkg of packages) {
      const priority: E2EPriority = config.criticalTools.includes(pkg) ? 'critical' : 'important';
      if (config.strategy === 'critical-only' && priority !== 'critical') continue;
      affected.push({ toolId: pkg, priority });
    }

    if (affected.length === 0 && config.strategy === 'always') {
      affected.push({ toolId: 'general', priority: 'nice-to-have' });
    }

    return { affectedTools: affected };
  }

  resolveGeneratedTestDir(config: ResolvedE2EConfig): string {
    // The Go toolchain ignores directories whose name begins with "." or "_"
    // (even when named explicitly), so the default `.ody-code/...` path is
    // unusable. Fall back to a module-internal, non-ignored directory.
    const segments = config.generatedTestDir.replace(/\\/g, '/').split('/').filter((s) => s.length > 0);
    const ignored = segments.some((s) => s.startsWith('.') || s.startsWith('_'));
    return ignored ? 'e2e_generated' : config.generatedTestDir;
  }

  async generateTestsForFeature(feature: Feature, _outputDir: string): Promise<TestFile[]> {
    const detection =
      (await this.detect(feature.projectRoot)) ??
      { kind: 'generic' as GoKind, framework: 'generic', buildTarget: '.' };
    const ident = goIdent(feature.toolId);
    const relativePath = `${ident.toLowerCase()}_e2e_test.go`;

    const content =
      detection.kind === 'http-server'
        ? this.renderHttpServerTest(ident, feature, detection.buildTarget)
        : this.renderGenericTest(ident, feature, detection.kind);

    return [{ relativePath, content }];
  }

  async runTests(absoluteTestPaths: string[], ctx: RunContext): Promise<TestSuiteResult[]> {
    if (absoluteTestPaths.length === 0) return [];
    const { kaos, config, projectRoot, signal } = ctx;
    // `go test` runs by package directory, not by file: run every unique dir
    // exactly once in a single invocation so we never double-count a package.
    const dirs = [...new Set(absoluteTestPaths.map((p) => this.relativeDir(projectRoot, p)))];
    const packageArgs = dirs.map((d) => `./${d}/`);
    const timeoutSeconds = Math.max(1, Math.ceil(config.testTimeout / 1000));
    const k = kaos.withCwd(projectRoot);

    const proc = await k.exec(
      'go', 'test', '-json',
      '-tags', 'e2e',
      `-timeout=${timeoutSeconds}s`,
      ...packageArgs,
    );

    const onAbort = () => { void proc.kill(); };
    if (signal?.aborted) onAbort();
    else signal?.addEventListener('abort', onAbort, { once: true });

    const stdoutChunks: Buffer[] = [];
    const stderrChunks: Buffer[] = [];
    proc.stdout.on('data', (chunk: Buffer) => stdoutChunks.push(chunk));
    proc.stderr.on('data', (chunk: Buffer) => stderrChunks.push(chunk));

    try {
      await proc.wait();
    } finally {
      signal?.removeEventListener('abort', onAbort);
    }

    const stdout = Buffer.concat(stdoutChunks).toString('utf-8');
    const suites = parseGoTestJson(stdout);
    if (suites.length > 0) return suites;

    // No parseable JSON usually means `go test` failed before running (e.g. a
    // compile error printed to stderr). Surface it as a single failed suite.
    const stderr = Buffer.concat(stderrChunks).toString('utf-8');
    return [{
      file: packageArgs.join(' '),
      status: 'failed' as const,
      duration: 0,
      tests: [{
        name: 'go test failed to run',
        status: 'failed' as const,
        failureMessages: [(stderr || stdout).slice(0, 2000)],
      }],
    }];
  }

  private renderHttpServerTest(ident: string, feature: Feature, buildTarget: string): string {
    return HTTP_SERVER_TEMPLATE
      .replaceAll('{{ident}}', ident)
      .replaceAll('{{moduleRoot}}', JSON.stringify(feature.projectRoot))
      .replaceAll('{{buildTarget}}', JSON.stringify(buildTarget));
  }

  private renderGenericTest(ident: string, feature: Feature, kind: GoKind): string {
    return GENERIC_TEMPLATE
      .replaceAll('{{ident}}', ident)
      .replaceAll('{{kind}}', kind)
      .replaceAll('{{toolId}}', feature.toolId);
  }

  /** Convert an absolute generated-file path into a module-relative dir. */
  private relativeDir(projectRoot: string, absoluteFile: string): string {
    const root = projectRoot.replace(/\\/g, '/').replace(/\/$/, '');
    const file = absoluteFile.replace(/\\/g, '/');
    const withoutRoot = file.startsWith(root + '/') ? file.slice(root.length + 1) : file;
    const slash = withoutRoot.lastIndexOf('/');
    return slash === -1 ? '.' : withoutRoot.slice(0, slash);
  }

  /** Detect whether `root` is a Go module and classify its shape. */
  private async detect(root: string): Promise<GoDetection | null> {
    const { existsSync, readFileSync, readdirSync } = await import('node:fs');
    if (!existsSync(join(root, 'go.mod'))) return null;

    const buildTarget = this.findBuildTarget(existsSync, readdirSync, readFileSync, root);

    try {
      const mod = readFileSync(join(root, 'go.mod'), 'utf-8');
      if (/gin-gonic\/gin/.test(mod)) return { kind: 'http-server', framework: 'gin', buildTarget };
      if (/labstack\/echo/.test(mod)) return { kind: 'http-server', framework: 'echo', buildTarget };
      if (/gofiber\/fiber/.test(mod)) return { kind: 'http-server', framework: 'fiber', buildTarget };
    } catch {
      // fall through to source scan
    }

    const goFiles = this.collectGoFiles(readdirSync, root, 300);
    let hasMain = existsSync(join(root, 'cmd'));
    for (const file of goFiles) {
      let content: string;
      try {
        content = readFileSync(file, 'utf-8');
      } catch {
        continue;
      }
      if (/"net\/http"/.test(content) && /(ListenAndServe|http\.Serve|\.Run\()/.test(content)) {
        return { kind: 'http-server', framework: 'net-http', buildTarget };
      }
      if (/package\s+main/.test(content) && /func\s+main\s*\(/.test(content)) {
        hasMain = true;
      }
    }

    return hasMain
      ? { kind: 'cli', framework: 'cli', buildTarget }
      : { kind: 'generic', framework: 'generic', buildTarget };
  }

  /**
   * Best-effort `go build` target for the server entrypoint. Prefers a `main`
   * package at the module root, then the common single `./cmd/<name>` layout,
   * falling back to "." (which the generated TODO comment tells the user to fix).
   */
  private findBuildTarget(
    existsSync: typeof import('node:fs').existsSync,
    readdirSync: typeof import('node:fs').readdirSync,
    readFileSync: typeof import('node:fs').readFileSync,
    root: string,
  ): string {
    try {
      for (const entry of readdirSync(root, { withFileTypes: true })) {
        if (entry.isFile() && entry.name.endsWith('.go') && !entry.name.endsWith('_test.go')) {
          try {
            if (/package\s+main/.test(readFileSync(join(root, entry.name), 'utf-8'))) return '.';
          } catch {
            // ignore unreadable file
          }
        }
      }
    } catch {
      // ignore unreadable root
    }
    const cmdDir = join(root, 'cmd');
    if (existsSync(cmdDir)) {
      try {
        const subs = readdirSync(cmdDir, { withFileTypes: true }).filter((e) => e.isDirectory());
        if (subs.length === 1) return `./cmd/${subs[0]!.name}`;
      } catch {
        // ignore unreadable cmd dir
      }
    }
    return '.';
  }

  /** Bounded recursive walk collecting `.go` source files (skips vendored/hidden dirs). */
  private collectGoFiles(
    readdirSync: typeof import('node:fs').readdirSync,
    root: string,
    limit: number,
  ): string[] {
    const results: string[] = [];
    const stack = [root];
    while (stack.length > 0 && results.length < limit) {
      const dir = stack.pop()!;
      const entries = (() => {
        try {
          return readdirSync(dir, { withFileTypes: true });
        } catch {
          return [];
        }
      })();
      for (const entry of entries) {
        const name = entry.name;
        if (entry.isDirectory()) {
          if (name.startsWith('.') || name.startsWith('_') || name === 'vendor' || name === 'node_modules') {
            continue;
          }
          stack.push(join(dir, name));
        } else if (name.endsWith('.go') && !name.endsWith('_test.go')) {
          results.push(join(dir, name));
          if (results.length >= limit) break;
        }
      }
    }
    return results;
  }
}
