#!/usr/bin/env node
/**
 * Generate game-design-skills.ts from the upstream game design skill library.
 *
 * Usage: pnpm --filter @odysseythink/agent-core tsx scripts/generate-game-design-skills.ts
 *
 * Reads all .md files from the upstream skill library directory, creates
 * SkillDefinition TypeScript source for each, and writes the generated module
 * to src/skill/builtin/game-design-skills.ts.
 *
 * Companion files (named like "parent--suffix.md") are merged into their
 * parent skill's content instead of becoming separate skills.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

const UPSTREAM_DIR =
  '/Users/ranwei/workspace/game_work/53ad898cdbc8734d8bb5c6a6ddf5cec4-0a2eae1c91f9a06a081de73f92f6ed86fbce1194';
const OUTPUT_PATH = join(
  import.meta.dirname,
  '..',
  'src',
  'skill',
  'builtin',
  'game-design-skills.ts',
);

interface FileEntry {
  name: string;
  path: string;
  content: string;
  isCompanion: boolean;
  parentStem: string;
}

function scanFiles(): FileEntry[] {
  const entries: FileEntry[] = [];
  for (const filename of readdirSync(UPSTREAM_DIR)) {
    if (!filename.endsWith('.md')) continue;
    if (filename === 'index.md') continue;
    const content = readFileSync(join(UPSTREAM_DIR, filename), 'utf-8');
    const doubleDash = filename.indexOf('--');
    const isCompanion = doubleDash !== -1;
    const stem = basename(filename, '.md');
    const parentStem = isCompanion ? stem.slice(0, doubleDash) : stem;
    entries.push({ name: stem, path: join(UPSTREAM_DIR, filename), content, isCompanion, parentStem });
  }
  return entries;
}

function slugToPascalCase(slug: string): string {
  return slug
    .split(/[-_]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

function buildSkillDef(entry: FileEntry, companionContent: string): string {
  const pascal = slugToPascalCase(entry.name);
  const varName = `GAME_DESIGN_${pascal.replace(/--/g, '_').toUpperCase()}_SKILL`;
  const combinedContent = entry.content + (companionContent ? '\n\n' + companionContent : '');
  const escaped = JSON.stringify(combinedContent);

  const descriptionLine = entry.content
    .split('\n')
    .find((l) => l.startsWith('description:'))
    ?.replace(/^description:\s*/, '')
    ?.trim() ?? entry.name;

  return `
export const ${varName}: SkillDefinition = {
  name: 'game-design/${entry.name}',
  description: ${JSON.stringify(descriptionLine)},
  path: 'builtin://game-design/${entry.name}',
  dir: 'builtin://game-design',
  content: ${escaped},
  source: 'builtin' as const,
  metadata: {
    type: 'prompt',
    hiddenInModes: ['normal', 'plan', 'design', 'product'] as const,
  },
};
`;
}

function generate(): void {
  const entries = scanFiles();

  // Group companions with their parents
  const companionMap = new Map<string, string>();
  const mainEntries: FileEntry[] = [];
  for (const entry of entries) {
    if (entry.isCompanion) {
      const existing = companionMap.get(entry.parentStem) ?? '';
      companionMap.set(entry.parentStem, existing + entry.content + '\n');
    } else {
      mainEntries.push(entry);
    }
  }

  mainEntries.sort((a, b) => a.name.localeCompare(b.name));

  const lines: string[] = [
    '// Auto-generated by scripts/generate-game-design-skills.ts',
    '// DO NOT EDIT MANUALLY. Run the script to regenerate.',
    '//',
    `// Generated at: ${new Date().toISOString()}`,
    '',
    "import type { SkillDefinition } from '../types';",
    '',
  ];

  const skillVarNames: string[] = [];

  for (const entry of mainEntries) {
    const companionContent = companionMap.get(entry.name) ?? '';
    const def = buildSkillDef(entry, companionContent);
    const match = def.match(/export const (\w+):/);
    if (match) skillVarNames.push(match[1]);
    lines.push(def);
  }

  lines.push('');

  lines.push('export const GAME_DESIGN_SKILLS: readonly SkillDefinition[] = [');
  for (const name of skillVarNames) {
    lines.push(`  ${name},`);
  }
  lines.push('];');
  lines.push('');

  lines.push("import type { SkillRegistry } from '../registry';");
  lines.push('');
  lines.push('export function registerGameDesignSkills(registry: SkillRegistry): void {');
  for (const name of skillVarNames) {
    lines.push(`  registry.registerBuiltinSkill(${name});`);
  }
  lines.push('}');
  lines.push('');

  writeFileSync(OUTPUT_PATH, lines.join('\n') + '\n', 'utf-8');
  console.log(`Generated ${OUTPUT_PATH} with ${mainEntries.length} skills`);
}

generate();
