import type { E2ETestGenerator, Feature, ProjectStructure, TestFile } from './types';
import { dirname, join, relative } from 'pathe';

function kebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

function importPath(fromFile: string, toFile: string): string {
  let rel = relative(dirname(fromFile), toFile);
  if (!rel.startsWith('.')) {
    rel = `./${rel}`;
  }
  return rel.replace(/\.ts$/, '');
}

const EXIT_PLAN_MODE_TEMPLATE = `import { describe, it, expect } from 'vitest';
import { ExitPlanModeTool } from '{{toolImport}}';
import { testAgent } from '{{harnessImport}}';

describe('{{toolId}} E2E', () => {
  it('constructs the tool and returns the correct name', () => {
    const ctx = testAgent();
    const tool = new ExitPlanModeTool(ctx.agent, ctx.agent.kaos);
    expect(tool.name).toBe('ExitPlanMode');
  });

  it('returns an execution with approval rule', () => {
    const ctx = testAgent();
    const tool = new ExitPlanModeTool(ctx.agent, ctx.agent.kaos);
    const execution = tool.resolveExecution({});
    expect(execution).toHaveProperty('approvalRule');
  });
});
`;

const GENERIC_TOOL_TEMPLATE = `import { describe, it, expect } from 'vitest';

describe('{{toolId}} E2E', () => {
  it('smoke: placeholder exists for further test expansion', () => {
    // This test file was auto-generated by RunE2ETests.
    // Replace with real assertions as tool-specific coverage grows.
    expect('{{toolId}}').toBeTruthy();
  });
});
`;

export class TypeScriptVitestGenerator implements E2ETestGenerator {
  readonly id = 'typescript-vitest';

  async detectProjectStructure(root: string): Promise<ProjectStructure | null> {
    const pkgPath = join(root, 'package.json');
    try {
      const { existsSync, readFileSync } = await import('node:fs');
      if (!existsSync(pkgPath)) return null;
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
      const hasVitest =
        pkg.devDependencies?.vitest !== undefined ||
        pkg.dependencies?.vitest !== undefined ||
        existsSync(join(root, 'vitest.config.ts')) ||
        existsSync(join(root, 'vitest.config.js'));
      if (!hasVitest) return null;
      return { language: 'typescript', framework: 'nodejs', testTool: 'vitest', root };
    } catch {
      return null;
    }
  }

  async generateTestsForFeature(feature: Feature, outputDir: string): Promise<TestFile[]> {
    if (feature.toolId === 'ExitPlanModeTool') {
      return [{ relativePath: 'exit-plan-mode.e2e.test.ts', content: this.renderExitPlanModeTest(feature, outputDir) }];
    }
    return [{ relativePath: this.fileNameFor(feature.toolId), content: this.renderGenericTest(feature) }];
  }

  private fileNameFor(toolId: string): string {
    return `${kebabCase(toolId)}.e2e.test.ts`;
  }

  private renderExitPlanModeTest(feature: Feature, outputDir: string): string {
    const relativePath = join(outputDir, 'exit-plan-mode.e2e.test.ts');
    const toolSrc = join(feature.projectRoot, 'src/tools/builtin/planning/exit-plan-mode.ts');
    const harnessSrc = join(feature.projectRoot, 'test/agent/harness/agent.ts');
    return EXIT_PLAN_MODE_TEMPLATE
      .replace(/\{\{toolId\}\}/g, feature.toolId)
      .replace(/\{\{toolImport\}\}/g, importPath(relativePath, toolSrc))
      .replace(/\{\{harnessImport\}\}/g, importPath(relativePath, harnessSrc));
  }

  private renderGenericTest(feature: Feature): string {
    return GENERIC_TOOL_TEMPLATE.replace(/\{\{toolId\}\}/g, feature.toolId);
  }
}
