import type {
  E2ETestGenerator,
  Feature,
  ImpactAnalysisResult,
  ProjectStructure,
  RunContext,
  TestCaseResult,
  TestFile,
  TestSuiteResult,
} from './types';
import type { ResolvedE2EConfig } from './config';
import { ImpactAnalyzer } from './impact-analyzer';
import { RecursiveImpactAnalyzer } from './recursive-impact-analyzer';
import { dirname, join, relative } from 'pathe';

function timestamp(): string {
  return new Date().toISOString().replaceAll(/[:.]/g, '-');
}

function parseVitestJson(json: Record<string, unknown>): TestSuiteResult[] {
  const testResults = (json['testResults'] ?? []) as Array<Record<string, unknown>>;
  return testResults.map((suite) => {
    const assertions = (suite['assertionResults'] ?? []) as Array<Record<string, unknown>>;
    const tests: TestCaseResult[] = assertions.map((a) => ({
      name: String(a['title'] ?? ''),
      status: (a['status'] as TestCaseResult['status']) ?? 'failed',
      failureMessages: (a['failureMessages'] as string[]) ?? [],
    }));
    return {
      file: String(suite['name'] ?? ''),
      status: (suite['status'] as TestSuiteResult['status']) ?? 'failed',
      duration: ((suite['endTime'] as number) ?? 0) - ((suite['startTime'] as number) ?? 0),
      tests,
    };
  });
}

function kebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

function importPath(fromFile: string, toFile: string): string {
  let rel = relative(dirname(fromFile), toFile);
  if (!rel.startsWith('.')) {
    rel = `./${rel}`;
  }
  return rel.replace(/\.ts$/, '');
}

const GENERIC_TOOL_TEMPLATE = `import { describe, it, expect } from 'vitest';

describe('{{toolId}} E2E', () => {
  it('smoke: placeholder exists for further test expansion', () => {
    // This test file was auto-generated by RunE2ETests.
    // Replace with real assertions as tool-specific coverage grows.
    expect('{{toolId}}').toBeTruthy();
  });
});
`;

export class TypeScriptVitestGenerator implements E2ETestGenerator {
  readonly id = 'typescript-vitest';

  async detectProjectStructure(root: string): Promise<ProjectStructure | null> {
    const pkgPath = join(root, 'package.json');
    try {
      const { existsSync, readFileSync } = await import('node:fs');
      if (!existsSync(pkgPath)) return null;
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
      const hasVitest =
        pkg.devDependencies?.vitest !== undefined ||
        pkg.dependencies?.vitest !== undefined ||
        existsSync(join(root, 'vitest.config.ts')) ||
        existsSync(join(root, 'vitest.config.js'));
      if (!hasVitest) return null;
      return { language: 'typescript', framework: 'nodejs', testTool: 'vitest', root };
    } catch {
      return null;
    }
  }

  analyzeImpact(changedFiles: string[], config: ResolvedE2EConfig, projectRoot?: string): ImpactAnalysisResult {
    const filesToAnalyze = config.recursiveAnalysisEnabled
      ? new RecursiveImpactAnalyzer().analyze(
          changedFiles,
          projectRoot ?? process.cwd(),
          'typescript',
          { maxDepth: config.maxRecursiveDepth },
        )
      : changedFiles;
    return ImpactAnalyzer.analyze(filesToAnalyze, config);
  }

  resolveGeneratedTestDir(config: ResolvedE2EConfig): string {
    return config.generatedTestDir;
  }

  async runTests(absoluteTestPaths: string[], ctx: RunContext): Promise<TestSuiteResult[]> {
    if (absoluteTestPaths.length === 0) return [];
    // Bound the number of concurrent vitest processes by chunking the files.
    const chunkSize = Math.max(1, ctx.config.maxConcurrency);
    const suites: TestSuiteResult[] = [];
    for (let i = 0; i < absoluteTestPaths.length; i += chunkSize) {
      suites.push(...(await this.runVitestChunk(absoluteTestPaths.slice(i, i + chunkSize), ctx)));
    }
    return suites;
  }

  private async runVitestChunk(files: string[], ctx: RunContext): Promise<TestSuiteResult[]> {
    const { kaos, config, projectRoot, signal } = ctx;
    const outputFile = join(dirname(files[0]!), `.vitest-output-${timestamp()}.json`);
    const k = kaos.withCwd(projectRoot);
    const proc = await k.exec(
      'pnpm', 'vitest', 'run',
      '--reporter=json',
      `--outputFile=${outputFile}`,
      `--testTimeout=${config.testTimeout}`,
      ...files,
    );

    const onAbort = () => { void proc.kill(); };
    if (signal?.aborted) onAbort();
    else signal?.addEventListener('abort', onAbort, { once: true });

    const stderrChunks: Buffer[] = [];
    proc.stderr.on('data', (chunk: Buffer) => stderrChunks.push(chunk));

    try {
      await proc.wait();
    } finally {
      signal?.removeEventListener('abort', onAbort);
    }

    try {
      const json = JSON.parse(await kaos.readText(outputFile)) as Record<string, unknown>;
      const suites = parseVitestJson(json);
      await this.tryRemove(kaos, outputFile);
      return suites;
    } catch {
      await this.tryRemove(kaos, outputFile);
      return [{
        file: '<vitest crash>',
        status: 'failed' as const,
        duration: 0,
        tests: [{
          name: 'vitest process failed',
          status: 'failed' as const,
          failureMessages: [Buffer.concat(stderrChunks).toString('utf-8').slice(0, 500)],
        }],
      }];
    }
  }

  private async tryRemove(kaos: RunContext['kaos'], path: string): Promise<void> {
    try {
      await kaos.exec('rm', path);
    } catch {
      // best-effort cleanup
    }
  }

  async generateTestsForFeature(feature: Feature, outputDir: string): Promise<TestFile[]> {
    if (feature.toolId === 'ExitPlanModeTool') {
      return [{ relativePath: 'exit-plan-mode.e2e.test.ts', content: this.renderExitPlanModeTest(feature, outputDir) }];
    }
    return [{ relativePath: this.fileNameFor(feature.toolId), content: this.renderGenericTest(feature) }];
  }

  private fileNameFor(toolId: string): string {
    return `${kebabCase(toolId)}.e2e.test.ts`;
  }

  private renderExitPlanModeTest(feature: Feature, outputDir: string): string {
    const relativePath = join(outputDir, 'exit-plan-mode.e2e.test.ts');
    const toolSrc = join(feature.projectRoot, 'src/tools/builtin/planning/exit-plan-mode.ts');
    const harnessSrc = join(feature.projectRoot, 'test/agent/harness/agent.ts');
    const toolImportPath = importPath(relativePath, toolSrc);
    const harnessImportPath = importPath(relativePath, harnessSrc);
    return [
      `import { describe, it, expect } from 'vitest';`,
      `import { ExitPlanModeTool } from '${toolImportPath}';`,
      `import { testAgent } from '${harnessImportPath}';`,
      '',
      `describe('${feature.toolId} E2E', () => {`,
      `  it('constructs the tool and returns the correct name', () => {`,
      `    const ctx = testAgent();`,
      `    const tool = new ExitPlanModeTool(ctx.agent, ctx.agent.kaos);`,
      `    expect(tool.name).toBe('ExitPlanMode');`,
      `  });`,
      '',
      `  it('returns an execution with approval rule', () => {`,
      `    const ctx = testAgent();`,
      `    const tool = new ExitPlanModeTool(ctx.agent, ctx.agent.kaos);`,
      `    const execution = tool.resolveExecution({});`,
      `    expect(execution).toHaveProperty('approvalRule');`,
      `  });`,
      `});`,
    ].join('\n');
  }

  private renderGenericTest(feature: Feature): string {
    return GENERIC_TOOL_TEMPLATE.replace(/\{\{toolId\}\}/g, feature.toolId);
  }
}
